-- ========================================
-- 01. 테이블 생성
-- ========================================

-- ========================================
-- 회사
-- ========================================
CREATE TABLE COMPANY (
                         company_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
                         name            VARCHAR2(100) NOT NULL,
                         biz_no          VARCHAR2(20),
                         use_yn          CHAR(1) DEFAULT 'Y' NOT NULL,
                         created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                         updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                         CONSTRAINT PK_COMPANY
                             PRIMARY KEY (company_id),

                         CONSTRAINT UQ_COMPANY_BIZ_NO
                             UNIQUE (biz_no),

                         CONSTRAINT CK_COMPANY_USE_YN
                             CHECK (use_yn IN ('Y', 'N'))
);


-- ========================================
-- 사용자
-- ========================================
CREATE TABLE USERS (
                       user_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
                       company_id      NUMBER NOT NULL,
                       login_id        VARCHAR2(50) NOT NULL,
                       password        VARCHAR2(255) NOT NULL,
                       name            VARCHAR2(50) NOT NULL,
                       role            VARCHAR2(20) NOT NULL,
                       use_yn          CHAR(1) DEFAULT 'Y' NOT NULL,
                       created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                       updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                       CONSTRAINT PK_USERS
                           PRIMARY KEY (user_id),

                       CONSTRAINT UQ_USERS_LOGIN_ID
                           UNIQUE (login_id),

                       CONSTRAINT FK_USERS_COMPANY
                           FOREIGN KEY (company_id)
                               REFERENCES COMPANY(company_id),

                       CONSTRAINT CK_USERS_ROLE
                           CHECK (role IN ('MASTER', 'DISPATCHER', 'ENGINEER')),

                       CONSTRAINT CK_USERS_USE_YN
                           CHECK (use_yn IN ('Y', 'N'))
);


-- ========================================
-- 장비 분류
-- ========================================
CREATE TABLE EQUIPMENT_CATEGORY (
                                    category_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                    parent_id       NUMBER,
                                    name            VARCHAR2(100) NOT NULL,
                                    use_yn          CHAR(1) DEFAULT 'Y' NOT NULL,
                                    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                    updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                                    CONSTRAINT PK_EQUIPMENT_CATEGORY
                                        PRIMARY KEY (category_id),

                                    CONSTRAINT FK_CATEGORY_PARENT
                                        FOREIGN KEY (parent_id)
                                            REFERENCES EQUIPMENT_CATEGORY(category_id),

                                    CONSTRAINT CK_CATEGORY_USE_YN
                                        CHECK (use_yn IN ('Y', 'N'))
);


-- ========================================
-- 공통 코드
-- ========================================
CREATE TABLE COMMON_CODE (
                             code_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
                             group_code      VARCHAR2(50) NOT NULL,
                             code            VARCHAR2(50) NOT NULL,
                             name            VARCHAR2(100) NOT NULL,
                             sort_order      NUMBER DEFAULT 0 NOT NULL,
                             use_yn          CHAR(1) DEFAULT 'Y' NOT NULL,
                             created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                             updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                             CONSTRAINT PK_COMMON_CODE
                                 PRIMARY KEY (code_id),

                             CONSTRAINT UQ_COMMON_CODE
                                 UNIQUE (group_code, code),

                             CONSTRAINT CK_COMMON_CODE_USE_YN
                                 CHECK (use_yn IN ('Y', 'N'))
);


-- ========================================
-- 장비
-- Java Equipment 엔티티와 컬럼명 통일
--
-- Java:
-- id       -> ID
-- name     -> NAME
-- type     -> TYPE
-- status   -> STATUS
-- location -> LOCATION
-- ========================================
CREATE TABLE EQUIPMENT (
                           id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
                           company_id      NUMBER,
                           category_id     NUMBER,
                           eq_no           VARCHAR2(50),
                           name            VARCHAR2(100) NOT NULL,
                           type            VARCHAR2(255),
                           status          VARCHAR2(255),
                           location        VARCHAR2(200),
                           status_code_id  NUMBER,
                           use_yn          CHAR(1) DEFAULT 'Y' NOT NULL,
                           created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                           updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                           CONSTRAINT PK_EQUIPMENT
                               PRIMARY KEY (id),

                           CONSTRAINT UQ_EQUIPMENT_EQ_NO
                               UNIQUE (eq_no),

                           CONSTRAINT FK_EQUIPMENT_COMPANY
                               FOREIGN KEY (company_id)
                                   REFERENCES COMPANY(company_id),

                           CONSTRAINT FK_EQUIPMENT_CATEGORY
                               FOREIGN KEY (category_id)
                                   REFERENCES EQUIPMENT_CATEGORY(category_id),

                           CONSTRAINT FK_EQUIPMENT_STATUS
                               FOREIGN KEY (status_code_id)
                                   REFERENCES COMMON_CODE(code_id),

                           CONSTRAINT CK_EQUIPMENT_USE_YN
                               CHECK (use_yn IN ('Y', 'N'))
);


-- ========================================
-- 장애
-- ========================================
CREATE TABLE FAILURE (
                         failure_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
                         equipment_id    NUMBER NOT NULL,
                         reporter_id     NUMBER NOT NULL,
                         type_code_id    NUMBER NOT NULL,
                         content         CLOB NOT NULL,
                         occurred_at     TIMESTAMP NOT NULL,
                         status_code_id  NUMBER NOT NULL,
                         created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                         updated_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                         CONSTRAINT PK_FAILURE
                             PRIMARY KEY (failure_id),

                         CONSTRAINT FK_FAILURE_EQUIPMENT
                             FOREIGN KEY (equipment_id)
                                 REFERENCES EQUIPMENT(id),

                         CONSTRAINT FK_FAILURE_REPORTER
                             FOREIGN KEY (reporter_id)
                                 REFERENCES USERS(user_id),

                         CONSTRAINT FK_FAILURE_TYPE
                             FOREIGN KEY (type_code_id)
                                 REFERENCES COMMON_CODE(code_id),

                         CONSTRAINT FK_FAILURE_STATUS
                             FOREIGN KEY (status_code_id)
                                 REFERENCES COMMON_CODE(code_id)
);


-- ========================================
-- 장애 배정
-- ========================================
CREATE TABLE ASSIGNMENT (
                            assign_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
                            failure_id       NUMBER NOT NULL,
                            engineer_id      NUMBER NOT NULL,
                            dispatcher_id    NUMBER NOT NULL,
                            priority_code_id NUMBER NOT NULL,
                            request_note     CLOB,
                            assigned_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                            CONSTRAINT PK_ASSIGNMENT
                                PRIMARY KEY (assign_id),

                            CONSTRAINT FK_ASSIGNMENT_FAILURE
                                FOREIGN KEY (failure_id)
                                    REFERENCES FAILURE(failure_id),

                            CONSTRAINT FK_ASSIGNMENT_ENGINEER
                                FOREIGN KEY (engineer_id)
                                    REFERENCES USERS(user_id),

                            CONSTRAINT FK_ASSIGNMENT_DISPATCHER
                                FOREIGN KEY (dispatcher_id)
                                    REFERENCES USERS(user_id),

                            CONSTRAINT FK_ASSIGNMENT_PRIORITY
                                FOREIGN KEY (priority_code_id)
                                    REFERENCES COMMON_CODE(code_id)
);


-- ========================================
-- 장애 조치
-- ========================================
CREATE TABLE FAILURE_ACTION (
                                action_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                assign_id    NUMBER NOT NULL,
                                cause        CLOB,
                                action       CLOB,
                                result       CLOB,
                                started_at   TIMESTAMP,
                                finished_at  TIMESTAMP,
                                created_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                                CONSTRAINT PK_FAILURE_ACTION
                                    PRIMARY KEY (action_id),

                                CONSTRAINT FK_FAILURE_ACTION_ASSIGNMENT
                                    FOREIGN KEY (assign_id)
                                        REFERENCES ASSIGNMENT(assign_id)
);


-- ========================================
-- 장애 상태 변경 이력
-- ========================================
CREATE TABLE STATUS_HISTORY (
                                history_id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                failure_id          NUMBER NOT NULL,
                                from_status_code_id NUMBER,
                                to_status_code_id   NUMBER NOT NULL,
                                changed_by          NUMBER NOT NULL,
                                changed_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                                CONSTRAINT PK_STATUS_HISTORY
                                    PRIMARY KEY (history_id),

                                CONSTRAINT FK_STATUS_HISTORY_FAILURE
                                    FOREIGN KEY (failure_id)
                                        REFERENCES FAILURE(failure_id),

                                CONSTRAINT FK_STATUS_HISTORY_FROM
                                    FOREIGN KEY (from_status_code_id)
                                        REFERENCES COMMON_CODE(code_id),

                                CONSTRAINT FK_STATUS_HISTORY_TO
                                    FOREIGN KEY (to_status_code_id)
                                        REFERENCES COMMON_CODE(code_id),

                                CONSTRAINT FK_STATUS_HISTORY_USER
                                    FOREIGN KEY (changed_by)
                                        REFERENCES USERS(user_id)
);