-- ========================================
-- 05. 엔지니어 담당 장비 관리
-- ========================================


-- ========================================
-- 엔지니어 담당 장비
-- ========================================

CREATE TABLE EQUIPMENT_MANAGER (
                                   manager_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                   equipment_id    NUMBER NOT NULL,
                                   engineer_id    NUMBER NOT NULL,
                                   assigned_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                                   ended_at      TIMESTAMP,
                                   use_yn        CHAR(1) DEFAULT 'Y' NOT NULL,

                                   CONSTRAINT PK_EQUIPMENT_MANAGER
                                       PRIMARY KEY (manager_id),

                                   CONSTRAINT FK_EQ_MANAGER_EQUIPMENT
                                       FOREIGN KEY (equipment_id)
                                           REFERENCES EQUIPMENT(equipment_id),

                                   CONSTRAINT FK_EQ_MANAGER_ENGINEER
                                       FOREIGN KEY (engineer_id)
                                           REFERENCES USERS(user_id),

                                   CONSTRAINT CK_EQ_MANAGER_USE_YN
                                       CHECK (use_yn IN ('Y', 'N')),

                                   CONSTRAINT CK_EQ_MANAGER_DATE
                                       CHECK (ended_at IS NULL OR ended_at >= assigned_at)
);


-- ========================================
-- 현재 담당 엔지니어 중복 방지
-- 장비 하나당 현재 담당 엔지니어는 한 명
-- ========================================

CREATE UNIQUE INDEX UX_EQUIPMENT_MANAGER_ACTIVE
    ON EQUIPMENT_MANAGER (
                          CASE
                              WHEN use_yn = 'Y'
        THEN equipment_id
    END
        );


-- ========================================
-- 담당 엔지니어 등록 예시
-- ========================================

INSERT INTO EQUIPMENT_MANAGER (
    equipment_id,
    engineer_id
)
VALUES (
           1,
           3
       );


COMMIT;