-- ========================================
-- 06. 장애 검토 / 반려
-- ========================================

CREATE TABLE FAILURE_REVIEW (
                                review_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                failure_id      NUMBER NOT NULL,
                                reviewer_id     NUMBER NOT NULL,
                                review_result   VARCHAR2(20) NOT NULL,
                                review_comment  CLOB,
                                reviewed_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                                CONSTRAINT PK_FAILURE_REVIEW
                                    PRIMARY KEY (review_id),

                                CONSTRAINT FK_FAILURE_REVIEW_FAILURE
                                    FOREIGN KEY (failure_id)
                                        REFERENCES FAILURE(failure_id),

                                CONSTRAINT FK_FAILURE_REVIEW_USER
                                    FOREIGN KEY (reviewer_id)
                                        REFERENCES USERS(user_id),

                                CONSTRAINT CK_FAILURE_REVIEW_RESULT
                                    CHECK (review_result IN ('APPROVED', 'REJECTED'))
);


-- 검토 승인 예시
INSERT INTO FAILURE_REVIEW (
    failure_id,
    reviewer_id,
    review_result,
    review_comment
)
VALUES (
           1,
           2,
           'APPROVED',
           '장애 조치 내용을 검토했으며 정상 처리된 것으로 확인함.'
       );

COMMIT;