-- ========================================
-- 07. 감사 로그
-- ========================================


-- ========================================
-- 감사 로그
-- ========================================

CREATE TABLE AUDIT_LOG (
                           audit_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
                           user_id         NUMBER,
                           action_type     VARCHAR2(20) NOT NULL,
                           table_name      VARCHAR2(100) NOT NULL,
                           record_id       NUMBER,
                           action_detail   CLOB,
                           created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

                           CONSTRAINT PK_AUDIT_LOG
                               PRIMARY KEY (audit_id),

                           CONSTRAINT FK_AUDIT_LOG_USER
                               FOREIGN KEY (user_id)
                                   REFERENCES USERS(user_id),

                           CONSTRAINT CK_AUDIT_LOG_ACTION
                               CHECK (action_type IN (
                                                      'CREATE',
                                                      'UPDATE',
                                                      'DELETE',
                                                      'LOGIN',
                                                      'LOGOUT'
                                   ))
);


-- ========================================
-- 장비 등록 로그
-- ========================================

INSERT INTO AUDIT_LOG (
    user_id,
    action_type,
    table_name,
    record_id,
    action_detail
)
VALUES (
           1,
           'CREATE',
           'EQUIPMENT',
           1,
           '장비 EQ-001 등록'
       );


-- ========================================
-- 장애 수정 로그
-- ========================================

INSERT INTO AUDIT_LOG (
    user_id,
    action_type,
    table_name,
    record_id,
    action_detail
)
VALUES (
           3,
           'UPDATE',
           'FAILURE',
           1,
           '장애 상태 변경 및 조치 완료'
       );


COMMIT;